#!/bin/sh

# Output the inclusion of the test suite header
echo '#include "test-suite.h"'

# Output the main function opening
echo '
int main(int argc, char *argv[])
{'

# Generate test calls from function declarations in the input file
grep -h "^void test_" "$1" | sed -e "s/^void //g" -e "s/(void)/();/g"

# Output the main function closing
echo '
    return 0;
}'
