#!/bin/sh
# tools/gen-version-file

VERSION=$(git describe --tags --dirty --always 2>/dev/null)

if [ -z "$VERSION" ]; then
    VERSION="v1.0.0"  # Default version
fi

echo "#define LIBTRADING_VERSION \"$VERSION\""
